import { readFileSync } from 'node:fs';
// as/flags.ts, generated by scripts/generate-flags.ts: each name in a flag
// family stands for the bit of the Pawn constant it came from.
// @ts-ignore - bun:test types not available during type checking
import { expect, test } from 'bun:test';

const flags = readFileSync('as/flags.ts', 'utf8');
const constants = readFileSync('as/constants.ts', 'utf8');

function constant(name: string): number {
	const m = constants.match(new RegExp(`^export const ${name}: i32 = (-?\\d+);`, 'm'));
	if (!m) throw new Error(`${name} is not in as/constants.ts`);
	return Number(m[1]);
}

/** The bit a name stands for: its place in the family's names picks its bit. */
function member(family: string, name: string): number {
	const upper = family.replace(/[A-Z]/g, (c, i) => (i ? '_' : '') + c).toUpperCase();
	const block = flags.match(new RegExp(`export const ${upper} = new FlagFamily\\(\\s*\\[([^\\]]*)\\],\\s*\\[([^\\]]*)\\]`));
	if (!block) throw new Error(`family ${family} is not in as/flags.ts`);
	const names = block[1].split(',').map(n => n.trim().replace(/"/g, ''));
	const bits = block[2].split(',').map(b => Number(b.trim().replace('1 << ', '')));
	const at = names.indexOf(name);
	if (at < 0) throw new Error(`${family} "${name}" is missing`);
	if (!flags.includes(`| "${name}"`)) throw new Error(`"${name}" is not in the ${family} type`);
	return (1 << bits[at]) | 0;
}

test.each([
	['HideHud', 'money', 'HIDEHUD_MONEY'],
	['HideHud', 'observerCrosshair', 'HIDEHUD_OBSERVER_CROSSHAIR'],
	['Button', 'jump', 'IN_JUMP'],
	['Button', 'attack2', 'IN_ATTACK2'],
	['EntityFlag', 'onGround', 'FL_ONGROUND'],
	['EntityFlag', 'dormant', 'FL_DORMANT'],
	['Effect', 'noDraw', 'EF_NODRAW'],
	['Damage', 'fall', 'DMG_FALL'],
	['WeaponState', 'm4a1Silenced', 'WPNSTATE_M4A1_SILENCED'],
	['WeaponState', 'shieldDrawn', 'WPNSTATE_SHIELD_DRAWN'],
	['PhysicsFlag', 'onLadder', 'PFLAG_ONLADDER'],
	['PhysicsFlag', 'observer', 'PFLAG_OBSERVER'],
])('%s.%s is %s', (family: string, name: string, pawn: string) => {
	expect(member(family, name)).toBe(constant(pawn));
});

test('a value of several bits is not a member', () => {
	expect(flags).not.toMatch(/\tGibCorpse = /);
	expect(flags).toContain('DMG_GIB_CORPSE = 737');
});

test('an alias of another bit is not a second name', () => {
	// PFLAG_ONSWING is PFLAG_ONLADDER's bit.
	expect(flags).not.toContain('"onSwing"');
});
