import { readFileSync } from 'node:fs';
/**
 * The three faces of the native table have to agree.
 *
 * wamrc believes the signature file; the module believes its thunks; the
 * plugin believes the declarations. A disagreement about arity is caught at
 * compile time (the patched wamrc warns and drops that native to the slow
 * path), but a `$` or `*` in a signature would pass every check and
 * miscompile in silence — a native given `($)i` in the table and `(i)i` at
 * runtime returned 985861440 instead of 200000.
 *
 * Generated by scripts/generate-wasm-api.ts; run `bun run generate` first.
 */
// @ts-ignore - bun:test types not available during type checking
import { describe, expect, test } from 'bun:test';

const signatures = readFileSync('runtime/natives.txt', 'utf-8');
const declarations = readFileSync('as/natives.ts', 'utf-8');
const thunks = readFileSync('runtime/src/natives.h', 'utf-8');

/** name -> how many cells the signature says it takes */
function signatureArities(): Map<string, number> {
	const arities = new Map<string, number>();

	for (const line of signatures.split('\n')) {
		if (!line.trim() || line.startsWith('#')) continue;

		const [name, signature] = line.trim().split(/\s+/);
		const params = signature.slice(1, signature.indexOf(')'));
		arities.set(name, params.length);
	}

	return arities;
}

describe('the generated native table', () => {
	const arities = signatureArities();

	test('describes every parameter as a cell', () => {
		for (const line of signatures.split('\n')) {
			if (!line.trim() || line.startsWith('#')) continue;
			// The result is a cell too, or an f64 (`F`) for the module's own
			// clocks: Date.now, performance.now and Math.random's seed - and for
			// a number field plugins add to Player, which crosses as an f64 both ways
			// (player_data_get, player_data_set).
			expect(line).toMatch(/^\S+ \(i*F?\)[iF]?$/);
		}
	});

	test('declares the same arity to the plugin as to wamrc', () => {
		// A typed native keeps its raw import private, under __raw_; an untyped
		// one exports it under its own name. Both are the arity wamrc sees.
		const declared = declarations.matchAll(
			/@external\("env", "(\w+)"\)\n(?:export )?declare function \w+\(([^)]*)\)/g,
		);

		let checked = 0;

		for (const [, name, params] of declared) {
			const count = params.trim() ? params.split(',').length : 0;
			expect([name, arities.get(name)]).toEqual([name, count]);
			checked++;
		}

		expect(checked).toBeGreaterThan(500);
	});

	test('gives the module a thunk of that arity for each one', () => {
		const written = thunks.matchAll(/static int32_t w_(\w+)\(([^)]*)\)/g);

		let checked = 0;

		for (const [, name, params] of written) {
			// Every thunk takes the exec env, which is not a wasm parameter.
			const count = params.split(',').length - 1;
			expect([name, arities.get(name)]).toEqual([name, count]);
			checked++;
		}

		expect(checked).toBeGreaterThan(500);
	});

	test('registers each thunk under the name the plugin imports', () => {
		const table = thunks.slice(thunks.indexOf('g_generatedNatives'));

		for (const [, name, fn, signature] of table.matchAll(
			/\{ "(\w+)", \(void \*\)w_(\w+), "([^"]+)", NULL \}/g,
		)) {
			expect(fn).toBe(name);
			expect(signature).toBe(`(${'i'.repeat(arities.get(name) ?? -1)})i`);
		}
	});
});
