import { readFileSync } from 'node:fs';
/**
 * The three faces of the native table have to agree.
 *
 * wamrc believes the signature file; the module believes its thunks; the
 * plugin believes the declarations. A disagreement about arity is caught at
 * compile time (the patched wamrc warns and drops that native to the slow
 * path), but a `$` or `*` in a signature would pass every check and
 * miscompile in silence — a native given `($)i` in the table and `(i)i` at
 * runtime returned 985861440 instead of 200000.
 *
 * Generated by scripts/generate-wasm-api.ts; run `bun run generate` first.
 */
// @ts-ignore - bun:test types not available during type checking
import { describe, expect, test } from 'bun:test';

const signatures = readFileSync('runtime/natives.txt', 'utf-8');
const declarations = readFileSync('as/natives.ts', 'utf-8');
const thunks = readFileSync('runtime/src/natives.h', 'utf-8');
const constants = readFileSync('as/constants.ts', 'utf-8');

/** The body of a native's thunk. */
function thunkOf(name: string): string {
	const thunk = thunks.slice(thunks.indexOf(`static int32_t w_${name}(`));
	return thunk.slice(0, thunk.indexOf('\n}'));
}

/** name -> how many cells the signature says it takes */
function signatureArities(): Map<string, number> {
	const arities = new Map<string, number>();

	for (const line of signatures.split('\n')) {
		if (!line.trim() || line.startsWith('#')) continue;

		const [name, signature] = line.trim().split(/\s+/);
		const params = signature.slice(1, signature.indexOf(')'));
		arities.set(name, params.length);
	}

	return arities;
}

describe('the generated native table', () => {
	const arities = signatureArities();

	test('describes every parameter as a cell', () => {
		for (const line of signatures.split('\n')) {
			if (!line.trim() || line.startsWith('#')) continue;
			// The result is a cell too, or an f64 (`F`) for the module's own
			// clocks: Date.now, performance.now and Math.random's seed - and for
			// a number field plugins add to Player, which crosses as an f64 both ways
			// (player_data_get, player_data_set).
			expect(line).toMatch(/^\S+ \(i*F?\)[iF]?(?: \S+)?$/);
		}
	});

	test('says how a native with a buffer passes each argument, on a line wamrc reads whole', () => {
		for (const line of signatures.split('\n')) {
			if (!line.trim() || line.startsWith('#')) continue;
			// wamrc reads a line into 256 bytes: a longer one would go on as a line of its own.
			expect(line.length).toBeLessThan(255);
			const [name, signature, crossing] = line.split(' ');
			if (!crossing) continue;
			const params = signature.slice(1, signature.indexOf(')')).length;
			expect([name, crossing.split(',').length]).toEqual([name, params]);
			for (const each of crossing.split(',')) expect(each).toMatch(/^(?:v|s|\[(?:\d+|[an]\d+)>?)$/);
		}
		// A buffer the native fills, its length after it, a string going in.
		expect(signatures).toMatch(/^add \(iiii\)i \[a1>,v,s,v$/m);
		expect(signatures).toMatch(/^admins_flush \(\)i$/m);
	});

	test('declares the same arity to the plugin as to wamrc', () => {
		// A typed native keeps its raw import private, under __raw_; an untyped
		// one exports it under its own name. Both are the arity wamrc sees.
		const declared = declarations.matchAll(
			/@external\("env", "(\w+)"\)\n(?:export )?declare function \w+\(([^)]*)\)/g,
		);

		let checked = 0;

		for (const [, name, params] of declared) {
			const count = params.trim() ? params.split(',').length : 0;
			expect([name, arities.get(name)]).toEqual([name, count]);
			checked++;
		}

		expect(checked).toBeGreaterThan(500);
	});

	test('gives the module a thunk of that arity for each one', () => {
		const written = thunks.matchAll(/static int32_t w_(\w+)\(([^)]*)\)/g);

		let checked = 0;

		for (const [, name, params] of written) {
			// Every thunk takes the exec env, which is not a wasm parameter.
			const count = params.split(',').length - 1;
			expect([name, arities.get(name)]).toEqual([name, count]);
			checked++;
		}

		expect(checked).toBeGreaterThan(500);
	});

	test('registers each thunk under the name the plugin imports', () => {
		const table = thunks.slice(thunks.indexOf('g_generatedNatives'));

		for (const [, name, fn, signature] of table.matchAll(
			/\{ "(\w+)", \(void \*\)w_(\w+), "([^"]+)", NULL \}/g,
		)) {
			expect(fn).toBe(name);
			expect(signature).toBe(`(${'i'.repeat(arities.get(name) ?? -1)})i`);
		}
	});

	test('copies a buffer of the size its include names, both ways', () => {
		// get_players(players[MAX_PLAYERS], ...): the size is a name the
		// includes define, 32 or 33 as the AMX Mod X version says.
		const players = Number(constants.match(/^export const MAX_PLAYERS: i32 = (\d+);/m)![1]);
		expect([32, 33]).toContain(players);

		const body = thunkOf('get_players');
		expect(body).not.toContain('f.fits');
		expect(body).toContain(`p[1] = f.in(a0, ${players});`);
		expect(body).toContain(`f.out(a0, ${players}, p[1]);`);
		expect(signatures).toMatch(new RegExp(`^get_players \\(iiii\\)i(?: \\[${players}>,|$)`, 'm'));
	});

	test('copies a buffer of a guessed size as far as the plugin\'s memory goes, the same both ways', () => {
		// trim(text[]): no size and no length beside it, so a guess. Asked for a
		// whole 128 cells from a buffer at the end of the memory, the module
		// would refuse them and fail the plugin's call with "out of bounds
		// memory access"; it counts what fits once and copies that both ways.
		const body = thunkOf('trim');
		expect(body).toContain('int32_t n0 = f.fits(a0, 128);');
		expect(body).toContain('p[1] = f.in(a0, n0);');
		expect(body).toContain('f.out(a0, n0, p[1]);');
	});
});
