import { readFileSync } from 'node:fs';
// as/hooks.ts, generated by scripts/generate-hooks.ts: each game event - a reapi
// hookchain, a Ham Sandwich function, or both - is an event class whose fields
// have the types the include documents, written through the argument number
// the backend counts, with a typed registrar per event.
// @ts-ignore - bun:test types not available during type checking
import { expect, test } from 'bun:test';

const hooks = readFileSync('as/hooks.ts', 'utf8');

function classBody(name: string): string {
	const m = hooks.match(new RegExp(`export class ${name} extends HookEvent \\{([\\s\\S]*?)\\n\\}`));
	if (!m) throw new Error(`${name} is not in as/hooks.ts`);
	return m[1];
}

test('take_damage: damage is a float argument 4, the victim is read only', () => {
	const body = classBody('TakeDamageEvent');
	expect(body).toContain('get damage(): number { return cellFloat(this.__cell(3)); }');
	expect(body).toContain('set damage(value: number) { this.__set(3, ATYPE_FLOAT, floatCell(value)); }');
	expect(body).toContain('get player(): Player { return new Player(this.__cell(0)); }');
	expect(body).toContain('get attacker(): Player { return new Player(this.__cell(2)); }');
	expect(body).not.toContain('set player(');
	expect(body).not.toContain('set attacker(');
	expect(body).toContain('get damageType(): Damage[]');
	expect(body).toContain('get result(): number { return this.__resultCell(ATYPE_INTEGER); }');
	// Read only: a handler answers by returning.
	expect(body).not.toContain('set result(');
});

test('fall damage returns a float result', () => {
	expect(classBody('FlPlayerFallDamageEvent')).toContain('get result(): number { return cellFloat(this.__resultCell(ATYPE_FLOAT)); }');
});

test('start_sound: the sample is a string that can be rewritten', () => {
	const body = classBody('StartSoundEvent');
	expect(body).toContain('get sample(): string { return this.__text(3); }');
	expect(body).toContain('set sample(value: string) { this.__setText(3, value); }');
});

test('a keyword never becomes a field name', () => {
	expect(hooks).not.toMatch(/\tget (override|default|class|type)\(/);
});

test('game.addEventListener: every chain is a key, with its event and its answer', () => {
	expect(hooks).toMatch(/export interface GameEventMap \{[\s\S]*\ttakeDamage: TakeDamageEvent;/);
	expect(hooks).toMatch(/export interface GameAnswerMap \{[\s\S]*\ttakeDamage: number;/);
	// A chain with nothing to answer takes a listener that returns nothing.
	expect(hooks).toMatch(/export interface GameAnswerMap \{[\s\S]*\tplayerSpawn: void;/);
	// The chain is registered once per side, however many listeners it gets.
	expect(hooks).toContain('if (!post && !takeDamagePreHooked) { takeDamagePreHooked = true; hook("take_damage", takeDamageFirePre, false); }');
	expect(hooks).toContain(`ERROR("a playerSpawn listener cannot answer: the game's function returns nothing")`);
});

test('an answer is the chain result, and in a pre hook it stops the chain', () => {
	expect(hooks).toContain('event.__answer(ATYPE_BOOL, answer ? 1 : 0, post);');
	expect(hooks).toContain('if (!post) return;');
	expect(hooks).toContain('if (!(isBoolean<R>())) ERROR("a canPlayerHearPlayer handler answers with boolean");');
});

test('listener and sender are players', () => {
	const body = classBody('CanPlayerHearPlayerEvent');
	expect(body).toContain('get listener(): Player');
	expect(body).toContain('get sender(): Player');
});

test('preventDefault and stopImmediatePropagation are on every event', () => {
	expect(hooks).toContain('preventDefault() {');
	expect(hooks).toContain('stopImmediatePropagation() {');
	expect(hooks).toContain('__outcome(this.__ham ? HAM_SUPERCEDE : HC_BREAK);');
});

test('chains reapi leaves the return type out of answer as ReGameDLL returns', () => {
	// regamedll_api.h: IHookChain<bool, ...> IReGameHook_RoundEnd and friends.
	// Read as void, preventDefault() on round_end blocked without an answer and
	// reapi refused it on every map change.
	expect(classBody('RoundEndEvent')).toContain('preventDefault(): void { this.__block(ATYPE_BOOL); }');
	expect(classBody('ChooseTeamEvent')).toContain('preventDefault(): void { this.__block(ATYPE_INTEGER); }');
	expect(hooks).toContain('SetHookChainReturn(atype, atype == ATYPE_FLOAT ? floatCell(0.0) : 0);');
	expect(classBody('TakeHealthEvent')).toContain('get result(): number');
	expect(classBody('HasRestrictItemEvent')).toContain('get result(): boolean');
});

test('a Pawn enum argument is a union of names, from the include', () => {
	const roundEnd = classBody('RoundEndEvent');
	expect(roundEnd).toContain('get winner(): RoundWinner { return roundWinnerName(this.__cell(0)); }');
	expect(roundEnd).toContain('get reason(): RoundEndReason { return roundEndReasonName(this.__cell(1)); }');
	expect(roundEnd).toContain('get delay(): number');
	expect(classBody('CanSwitchTeamEvent')).toContain('get team(): Team');
	expect(classBody('ChooseTeamEvent')).toContain('get choice(): TeamChoice');
	expect(classBody('BuyWeaponByWeaponIdEvent')).toContain('get weapon(): WeaponKind');
	expect(classBody('AddAccountEvent')).toContain('get reason(): RewardReason');
	expect(classBody('HasRestrictItemEvent')).toContain('get restriction(): ItemRestriction');
	expect(classBody('HasRestrictItemEvent')).toContain('get item(): ItemKind');
	expect(classBody('PainEvent')).toContain('get lastHitGroup(): HitGroup');
	expect(classBody('SetAnimationEvent')).toContain('get playerAnim(): PlayerAnimation');
	expect(classBody('AddResourceEvent')).toContain('get resourceType(): ResourceType');
	expect(classBody('AddResourceEvent')).toContain('get resourceIndex(): number');
	expect(classBody('OnEventEvent')).toContain('get gameEvent(): BotEvent');
	expect(classBody('ShowVguiMenuEvent')).toContain('get menu(): VguiMenu');
	expect(classBody('SendDeathMessageEvent')).toContain('get flags(): DeathMessageFlag[]');
	expect(classBody('SendDeathMessageEvent')).toContain('get rarity(): KillRarity[]');
	expect(classBody('ThrowGrenadeEvent')).toContain('get velocity(): Vector');
	expect(classBody('HintMessageExEvent')).toContain('get displayIfHintsOff(): boolean');

	// The values are the include's: ROUND_TARGET_SAVED is 12, VGUI_Menu_Class_CT 27, t_eventscript 5.
	expect(hooks).toContain('case 12: return "targetSaved";');
	expect(hooks).toContain('case 27: return "classCT";');
	expect(hooks).toContain('case 5: return "eventscript";');
	// ITEM_NONE is -1, ITEM_DEFUSEKIT 32, HITGROUP_LEFTARM 4: the names HitGroup already has.
	expect(hooks).toContain('case -1: return "none";');
	expect(hooks).toContain('case 32: return "defusekit";');
	expect(hooks).toContain('case 4: return "leftArm";');
	expect(hooks).toMatch(/export type TeamChoice =\n\t\| "TERRORIST"\n\t\| "CT"\n\t\| "VIP"\n\t\| "auto"\n\t\| "SPECTATOR"\n\t\| "unknown";/);
	expect(hooks).toContain('["Headshot", "KillerBlind", "NoScope", "Penetrated", "ThruSmoke", "AssistedFlash", "DominationBegan", "Domination", "Revenge", "InAir"]');
	// No Pawn-dodge names are left.
	expect(hooks).not.toMatch(/\tget \w+Value\(/);
});

test('a Ham Sandwich function reapi has no chain for is an event of its own, named for the action', () => {
	const body = classBody('PrimaryAttackEvent');
	expect(body).toContain('private static readonly ham: i32 = Ham_Weapon_PrimaryAttack;');
	expect(body).toContain('get weapon(): Weapon { return new Weapon(this.__cell(0)); }');
	expect(hooks).toMatch(/export interface GameEventMap \{[\s\S]*\tprimaryAttack: PrimaryAttackEvent;/);
	// Every argument Ham Sandwich takes back is writable, an entity and a vector too.
	expect(classBody('UseEvent')).toContain('set caller(value: Entity) { this.__setEntity(1, value.id); }');
	expect(classBody('BodyTargetEvent')).toContain('set from(value: Vector) { this.__setVector(1, value); }');
	expect(classBody('TeamIdEvent')).toContain('get result(): string { return this.__resultText(); }');
	// No event is named after a backend or a C++ class.
	expect(hooks).not.toMatch(/^\t(?:ham|base|rg|cbase)\w*: \w+Event;/im);
});

test('the same function under reapi and Ham Sandwich is one event: reapi for its own class, Ham Sandwich for another', () => {
	expect(classBody('TakeDamageEvent')).toContain('private static readonly ham: i32 = Ham_TakeDamage;');
	expect(classBody('TakeDamageEvent')).toContain('get entity(): Entity');
	// Without reapi, Ham Sandwich hears the chain's own class too: "player".
	expect(hooks).toContain('if ((classname.length > 0 && classname != "player") || !__hasReapi()) { takeDamageHams.listen(classname.length > 0 ? classname : "player", post, takeDamageFire).push(entry); return; }');
	// A weapon chain's own class is every weapon: a class narrows it to Ham Sandwich, and without reapi it hooks every weapon's.
	expect(hooks).toContain('if ((classname.length > 0) || !__hasReapi()) { canDeployHams.listen(classname.length > 0 ? classname : EVERY_WEAPON, post, canDeployFire).push(entry); return; }');
	// A chain of ReGameDLL's own says so on a server without reapi, once, and is not added.
	expect(hooks).toContain('if (!__hasReapi()) { __sayOnce("roundEnd needs ReAPI, which this server does not have: its listeners are never called"); return; }');
	expect(hooks).toMatch(/\tspawn: SpawnEvent;/);
	expect(hooks).not.toContain('basePlayerSpawn');
	expect(hooks).toMatch(/\tgameThink: GameThinkEvent;/);
	expect(hooks).toMatch(/\tthink: ThinkEvent;/);
});
