import { readFileSync } from 'node:fs';
// as/hooks.ts, generated by scripts/generate-hooks.ts: each game event - a reapi
// hookchain, a Ham Sandwich function, or both - is an event class whose fields
// have the types the include documents, written through the argument number
// the backend counts, with a typed registrar per event.
// @ts-ignore - bun:test types not available during type checking
import { expect, test } from 'bun:test';

const hooks = readFileSync('as/hooks.ts', 'utf8');

function classBody(name: string): string {
	const m = hooks.match(new RegExp(`export class ${name} extends HookEvent \\{([\\s\\S]*?)\\n\\}`));
	if (!m) throw new Error(`${name} is not in as/hooks.ts`);
	return m[1];
}

test('take_damage: damage is a float argument 4, the victim is read only', () => {
	const body = classBody('TakeDamageEvent');
	expect(body).toContain('get damage(): number { return cellFloat(this.__cell(3)); }');
	expect(body).toContain('set damage(value: number) { this.__set(3, floatCell(value)); }');
	expect(body).toContain('get player(): Player { return __playerOf(this.__cell(0)); }');
	expect(body).toContain('get attacker(): Player { return __playerOf(this.__cell(2)); }');
	expect(body).not.toContain('set player(');
	expect(body).not.toContain('set attacker(');
	expect(body).toContain('get damageType(): Damage[]');
	expect(body).toContain('get result(): number { return this.__resultCell(); }');
	// Read only: a handler answers by returning.
	expect(body).not.toContain('set result(');
});

test('fall damage returns a float result', () => {
	expect(classBody('FallDamageEvent')).toContain('get result(): number { return cellFloat(this.__resultCell()); }');
});

test('start_sound: the sound is a string that can be rewritten', () => {
	const body = classBody('StartSoundEvent');
	expect(body).toContain('get sound(): string { return this.__text(3); }');
	expect(body).toContain('set sound(value: string) { this.__setText(3, value); }');
});

test('a keyword never becomes a field name', () => {
	expect(hooks).not.toMatch(/\tget (override|default|class|type)\(/);
});

test('game.addEventListener: every chain is a key, with its event and its answer', () => {
	expect(hooks).toMatch(/export interface GameEventMap \{[\s\S]*\ttakeDamage: TakeDamageEvent;/);
	expect(hooks).toMatch(/export interface GameAnswerMap \{[\s\S]*\ttakeDamage: number;/);
	// A chain with nothing to answer takes a listener that returns nothing.
	expect(hooks).toMatch(/export interface GameAnswerMap \{[\s\S]*\tplayerSpawn: void;/);
	// The chain is registered once per side, however many listeners it gets,
	// and switched off with the side's last listener (ChainPhase), which also
	// has the module call one listener itself, with the event's object.
	expect(hooks).toContain('(post ? takeDamagePost() : takeDamagePre()).add(entry, "take_damage", post ? takeDamageFirePost : takeDamageFirePre, post, changetype<usize>(takeDamageEvent()), true);');
	// Not where the walk does more than call: playerSpawn passes over a player counted out.
	expect(hooks).toContain('changetype<usize>(playerSpawnEvent()), false);');
	expect(hooks).toContain('(post ? takeDamagePost() : takeDamagePre()).remove(fn);');
	expect(hooks).toContain(`ERROR("a playerSpawn listener cannot answer: the game's function returns nothing")`);
});

test('an answer is the chain result, and in a pre hook it stops the chain', () => {
	expect(hooks).toContain('event.__answer(answer ? 1 : 0, post);');
	expect(hooks).toContain('if (!post) break;');
	expect(hooks).toContain('if (!(isBoolean<R>())) ERROR("a canPlayerHearPlayer handler answers with boolean");');
});

test('listener and sender are players', () => {
	const body = classBody('CanPlayerHearPlayerEvent');
	expect(body).toContain('get listener(): Player');
	expect(body).toContain('get sender(): Player');
});

test('preventDefault and stopImmediatePropagation are on every event', () => {
	expect(hooks).toContain('preventDefault() {');
	expect(hooks).toContain('stopImmediatePropagation() {');
	expect(hooks).toContain('__outcome(OUTCOME_BREAK);');
});

test('chains reapi leaves the return type out of answer as ReGameDLL returns', () => {
	// regamedll_api.h: IHookChain<bool, ...> IReGameHook_RoundEnd and friends.
	// Read as void, preventDefault() on round_end blocked without an answer.
	expect(classBody('RoundEndEvent')).toContain('preventDefault(): void { this.__block(); }');
	expect(classBody('ChooseTeamEvent')).toContain('preventDefault(): void { this.__block(); }');
	// Blocked, the function answers the neutral value.
	expect(hooks).toContain('__chainSet(-1, 0);');
	expect(classBody('HealEvent')).toContain('get result(): number');
	expect(classBody('ItemRestrictedEvent')).toContain('get result(): boolean');
});

test('a Pawn enum argument is a union of names, from the include', () => {
	const roundEnd = classBody('RoundEndEvent');
	expect(roundEnd).toContain('get winner(): RoundWinner { return roundWinnerName(this.__cell(0)); }');
	expect(roundEnd).toContain('get reason(): RoundEndReason { return roundEndReasonName(this.__cell(1)); }');
	expect(roundEnd).toContain('get delay(): number');
	expect(classBody('CanSwitchTeamEvent')).toContain('get team(): Team');
	expect(classBody('ChooseTeamEvent')).toContain('get choice(): TeamChoice');
	expect(classBody('BuyWeaponEvent')).toContain('get weapon(): WeaponKind');
	expect(classBody('AddMoneyEvent')).toContain('get reason(): RewardReason');
	expect(classBody('ItemRestrictedEvent')).toContain('get restriction(): ItemRestriction');
	expect(classBody('ItemRestrictedEvent')).toContain('get item(): ItemKind');
	expect(classBody('PainEvent')).toContain('get lastHitGroup(): HitGroup');
	expect(classBody('SetAnimationEvent')).toContain('get animation(): PlayerAnimation');
	expect(classBody('AddResourceEvent')).toContain('get resourceType(): ResourceType');
	expect(classBody('AddResourceEvent')).toContain('get resourceIndex(): number');
	expect(classBody('GameEventEvent')).toContain('get gameEvent(): BotEvent');
	expect(classBody('ShowVguiMenuEvent')).toContain('get menu(): VguiMenu');
	expect(classBody('SendDeathMessageEvent')).toContain('get flags(): DeathMessageFlag[]');
	expect(classBody('SendDeathMessageEvent')).toContain('get rarity(): KillRarity[]');
	expect(classBody('ThrowGrenadeEvent')).toContain('get velocity(): Vector');
	expect(classBody('HintMessageEvent')).toContain('get displayIfHintsOff(): boolean');
	// reapi's raw parameters in the author's words: tracehandle, infobuffer, weapon_entity, `bool bReverse`.
	expect(classBody('TraceAttackEvent')).toContain('get trace(): number');
	expect(classBody('TraceAttackEvent')).toContain('get direction(): Vector');
	expect(classBody('UserInfoChangeEvent')).toContain('get info(): string');
	expect(classBody('BuyAmmoEvent')).toContain('get weapon(): Weapon');
	expect(classBody('PrecacheModelEvent')).toContain('get file(): string');
	expect(classBody('RecoilEvent')).toContain('get upMax(): number');
	expect(classBody('SpectateNextEvent')).toContain('get reverse(): boolean');
	expect(hooks).not.toMatch(/\tget [a-z]+_\w*\(|\tget arg\d+\(/);

	// The values are the include's: ROUND_TARGET_SAVED is 12, VGUI_Menu_Class_CT 27, t_eventscript 5.
	expect(hooks).toContain('case 12: return "targetSaved";');
	expect(hooks).toContain('case 27: return "classCT";');
	expect(hooks).toContain('case 5: return "eventscript";');
	// ITEM_NONE is -1, ITEM_DEFUSEKIT 32, HITGROUP_LEFTARM 4: the names HitGroup already has.
	expect(hooks).toContain('case -1: return "none";');
	expect(hooks).toContain('case 32: return "defusekit";');
	expect(hooks).toContain('case 4: return "leftArm";');
	expect(hooks).toMatch(/export type TeamChoice =\n\t\| "TERRORIST"\n\t\| "CT"\n\t\| "VIP"\n\t\| "auto"\n\t\| "SPECTATOR"\n\t\| "unknown";/);
	expect(hooks).toContain('["headshot", "killerBlind", "noScope", "penetrated", "throughSmoke", "assistedFlash", "dominationBegan", "domination", "revenge", "inAir"]');
	// No Pawn-dodge names are left.
	expect(hooks).not.toMatch(/\tget \w+Value\(/);
});

test('a Ham Sandwich function reapi has no chain for is an event of its own, named for the action', () => {
	const body = classBody('PrimaryAttackEvent');
	expect(body).toContain('private static readonly ham: i32 = Ham_Weapon_PrimaryAttack;');
	expect(body).toContain('get weapon(): Weapon { return new Weapon(this.__cell(0)); }');
	expect(hooks).toMatch(/export interface GameEventMap \{[\s\S]*\tprimaryAttack: PrimaryAttackEvent;/);
	// Every argument Ham Sandwich takes back is writable, an entity and a vector too.
	expect(classBody('UseEvent')).toContain('set caller(value: Entity) { this.__setEntity(1, value.id); }');
	expect(classBody('BodyTargetEvent')).toContain('set from(value: Vector) { this.__setVector(1, value); }');
	expect(classBody('TeamIdEvent')).toContain('get result(): string { return this.__resultText(); }');
	// No event is named after a backend or a C++ class.
	expect(hooks).not.toMatch(/^\t(?:ham|base|rg|cbase)\w*: \w+Event;/im);
});

test('the same function under reapi and Ham Sandwich is one event: reapi for its own class, Ham Sandwich for another', () => {
	expect(classBody('TakeDamageEvent')).toContain('private static readonly ham: i32 = Ham_TakeDamage;');
	expect(classBody('TakeDamageEvent')).toContain('get entity(): Entity');
	// Without ReGameDLL, the Ham Sandwich function hears the chain's own class too: "player".
	expect(hooks).toContain('if ((classname.length > 0 && classname != "player") || !__hasChains(false)) { takeDamageHams().add(classname.length > 0 ? classname : "player", post, takeDamageFire, entry); return; }');
	expect(hooks).toContain('if ((classname.length > 0 && classname != "player") || !__hasChains(false)) { takeDamageHams().remove(classname.length > 0 ? classname : "player", post, fn); return; }');
	// A weapon chain's own class is every weapon: a class narrows it to the Ham Sandwich function, and without ReGameDLL it hooks every weapon's.
	expect(hooks).toContain('if ((classname.length > 0) || !__hasChains(false)) { canDeployHams().add(classname.length > 0 ? classname : EVERY_WEAPON, post, canDeployFire, entry); return; }');
	// A chain of ReGameDLL's own that nothing on plain HLDS hears says so there, once, and is not added.
	expect(hooks).toContain('if (!__hasChains(false)) { __sayOnce("fallDamage needs ReGameDLL, which this server does not have: its listeners are never called"); return; }');
	// One a stock hook hears goes to its backend (as/hlds.ts), registered on
	// the first listener and switched off with the event's last.
	expect(hooks).toContain('if (!roundEndHldsHooked) { roundEndHldsHooked = true; roundEndHlds(roundEndFireHlds, roundEndBackend()); }');
	expect(hooks).toContain('roundEndBackend().set(roundEndPre().entries.count + roundEndPost().entries.count > 0);');
	expect(hooks).toContain('if (post && !newRoundPostHldsHooked) { newRoundPostHldsHooked = true; newRoundPostHlds(newRoundFireHlds, newRoundPostBackend()); }');
	expect(hooks).toContain('newRoundPostBackend().set(newRoundPost().entries.count > 0);');
	expect(hooks).toMatch(/\tspawn: SpawnEvent;/);
	expect(hooks).not.toContain('basePlayerSpawn');
	expect(hooks).toMatch(/\tgameThink: GameThinkEvent;/);
	expect(hooks).toMatch(/\tthink: ThinkEvent;/);
});

test('an event\'s objects are made on its first listener, not in the module\'s start', () => {
	// A module-level `new` would compile every event's classes into every plugin.
	expect(hooks).not.toMatch(/^const \w+ = new (ChainPhase|HamHooks|__Switch)\b/m);
	expect(hooks).toContain('if (made == null) takeDamagePreMade = made = new ChainPhase<TakeDamageEvent, number>();');
});
