import { readFileSync } from 'node:fs';
/**
 * Leaf natives - those that run no plugin code (scripts/leaf-natives.ts) -
 * and every other native.
 *
 * A leaf native's import is `@leaf`, so a plugin keeps no shadow-stack frame
 * around a call to it, and its thunk hands it a literal's kept cells. A
 * native that may call a plugin back - a forward, callfunc, a cvar written, a
 * command run, a Pawn plugin's native, a sort with a comparator - must stay
 * off the list and go the copy way: marked `@leaf`, a collection run by its
 * callback would free what the calling plugin still holds.
 *
 * Generated by scripts/generate-wasm-api.ts; run `bun run generate` first.
 */
// @ts-ignore - bun:test types not available during type checking
import { expect, test } from 'bun:test';
import { LEAF_NATIVES } from '../scripts/leaf-natives';

const signatures = readFileSync('runtime/natives.txt', 'utf-8');
const declarations = readFileSync('as/natives.ts', 'utf-8');
const thunks = readFileSync('runtime/src/natives.h', 'utf-8');

/** The body of a native's thunk. */
function thunkOf(name: string): string {
	const thunk = thunks.slice(thunks.indexOf(`static int32_t w_${name}(`));
	return thunk.slice(0, thunk.indexOf('\n}'));
}

/** A native's line of runtime/natives.txt. */
function lineOf(name: string): string {
	return signatures.split('\n').find(line => line.startsWith(`${name} (`)) ?? '';
}

/** The import's line in as/natives.ts. */
function importOf(name: string): string {
	return declarations.split('\n').find(line => line.startsWith(`@external("env", "${name}")`)) ?? '';
}

// Natives that call back, each in a way of its own: a Pawn plugin's
// natives (menu_core, universal_config), callfunc, a cvar written (its
// hooks), a client's command run, a task, a sort with a comparator.
const CALLING_BACK = ['mc_register_menu', 'cfg_get_value', 'callfunc_begin', 'callfunc_push_str', 'set_cvar_string', 'engclient_cmd', 'set_task', 'ArraySort'];

test('a native that may call back goes the copy way', () => {
	for (const name of CALLING_BACK) {
		expect(lineOf(name), name).not.toBe('');
		expect(lineOf(name).endsWith(' leaf'), name).toBe(false);
		expect(importOf(name).includes('@leaf'), name).toBe(false);
		expect(thunkOf(name).includes('keptText'), name).toBe(false);
		expect(thunkOf(name).includes('backTextLeaf'), name).toBe(false);
	}
	// ExecuteForward, server_cmd, client_cmd: variadic, through the dispatcher, which marks none.
	for (const name of ['ExecuteForward', 'server_cmd', 'client_cmd']) expect(lineOf(name), name).toBe('');
});

test('a leaf native is marked in all three places, and only a leaf native', () => {
	expect(thunkOf('strlen')).toContain('f.keptText(a0)');
	expect(thunkOf('get_user_name')).toContain('f.backTextLeaf(');
	for (const line of signatures.split('\n')) {
		const name = line.split(' ')[0];
		if (!name || line.startsWith('#') || !thunks.includes(`w_${name}(`)) continue;
		const leaf = LEAF_NATIVES.has(name);
		expect(line.endsWith(' leaf'), name).toBe(leaf);
		expect(importOf(name).includes('@leaf'), name).toBe(leaf);
		if (!leaf) expect(/keptText|backTextLeaf/.test(thunkOf(name)), name).toBe(false);
	}
});
