// Writes runtime/abi-lock.txt: the version being released and every import
// of its natives table, each with its shape (scripts/build-identity.ts).
//
//   bun run abi:lock    once package.json has the version to release
//
// Within a line an import keeps its shape: a plugin built for this release
// loads on every later patch's module only while each import it uses is
// there unchanged. `bun run generate` refuses a natives table that breaks the
// lock, and the release refuses a lock of another version than its own.
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { ABI_LOCK, coreVersion, shapeChanges } from './build-identity';

const core = fileURLToPath(new URL('..', import.meta.url));
const lock = join(core, ABI_LOCK);
const natives = readFileSync(join(core, 'runtime/natives.txt'), 'utf8');
const changed = existsSync(lock) ? shapeChanges(readFileSync(lock, 'utf8'), natives) : [];
if (changed.length) throw new Error(`${ABI_LOCK}: within a line an import keeps its shape - a new shape is a new import (a new name, such as name2):\n${changed.join('\n')}`);

const shapes = natives.split(/\r?\n/).filter(line => line && !line.startsWith('#'));
writeFileSync(lock, [
	'# GENERATED by scripts/abi-lock.ts at a release - do not edit',
	'# The imports of the release, each with its shape. Within its line an import',
	'# keeps its shape: a plugin built for this release loads on every later patch.',
	coreVersion(),
	...shapes,
	'',
].join('\n'));
console.log(`${ABI_LOCK}: ${coreVersion()}, ${shapes.length} imports`);
