// Generates runtime/src/embedded.h: the files the module writes into
// addons/amxts on startup (scripts/server-files.ts), as C string literals.
//
//   bun scripts/generate-embedded.ts    the last step of `bun run generate`
//
// Last, because the files are the generated API as a plugin sees it - with
// its tooltips written in (scripts/apply-docs.ts) - and the module carries it
// so that the API on a server always belongs to the module that runs it: a
// natives.ts from another build compiles calls the module has no thunk for,
// and a natives.txt from another build makes wamrc emit the wrong signature.
import { writeFileSync } from 'node:fs';
import { buildIdentity } from './build-identity';
import { serverFiles } from './server-files';

/**
 * MSVC refuses a string literal over 16380 bytes, so each file goes in as
 * pieces. The break is at a line ending, which keeps the generated header
 * readable when something has to be looked at by eye.
 */
function chunks(text: string): string {
	const pieces: string[] = [];
	let piece = '';

	// Each line with its own line ending: the file is written back as it is.
	for (const line of text.split(/(?<=\n)/)) {
		if (piece.length + line.length > 8000) {
			pieces.push(piece);
			piece = '';
		}
		piece += line;
	}

	if (piece) pieces.push(piece);
	return pieces.map(escapeForC).map(p => `\t"${p}"`).join(',\n');
}

function escapeForC(text: string): string {
	return text
		.replace(/\\/g, '\\\\')
		.replace(/"/g, '\\"')
		.replace(/\r/g, '')
		.replace(/\n/g, '\\n"\n\t"')
		.replace(/\?\?/g, '?\\?'); // ??= and friends are trigraphs to an old compiler
}

const files = serverFiles().map((file, index) => ({ ...file, name: `embedded_${index}` }));

writeFileSync(
	'./runtime/src/embedded.h',
	`// GENERATED by scripts/generate-embedded.ts - do not edit
// Source: scripts/server-files.ts
//
// What the module writes into addons/amxts on startup, so that the API a
// plugin imports always belongs to the module that will run it. Carrying them
// here rather than beside the module is the only way to be sure of that: the
// module's thunks, a plugin's imports and wamrc's signatures are three faces
// of one list and cannot travel separately.

// The build this module is of, which amxts-compile beside it has to be of too.
#define AMXTS_BUILD "${buildIdentity()}"

${files.map(f => `static const char *const ${f.name}[] = {\n${chunks(f.text)}\n};`).join('\n\n')}

struct EmbeddedFile {
	// Under addons/amxts.
	const char *path;
	const char *const *chunks;
	int count;
	// Whether the author owns this one, and it is written only when missing.
	int keep;
};

static const EmbeddedFile g_embedded[] = {
${files.map(f => `\t{ "${f.path}", ${f.name}, (int)(sizeof(${f.name}) / sizeof(${f.name}[0])), ${f.keep ? 1 : 0} },`).join('\n')}
};
`,
);

console.log(`runtime/src/embedded.h: ${files.length} files`);
