// Generates runtime/src/embedded.h: the files the module writes into
// addons/amxts on startup (scripts/server-files.ts), and the natives table a
// plugin's imports are checked against (runtime/natives.txt), as C string
// literals.
//
//   bun scripts/generate-embedded.ts    the last step of `bun run generate`
//
// Last, because the natives table is the generated API's.
import { readFileSync, writeFileSync } from 'node:fs';
import { abiIdentity, buildIdentity } from './build-identity';
import { pluginList } from './server-files';

/**
 * MSVC refuses a string literal over 16380 bytes, so each file goes in as
 * pieces. The break is at a line ending, which keeps the generated header
 * readable when something has to be looked at by eye.
 */
function chunks(text: string): string {
	const pieces: string[] = [];
	let piece = '';

	// Each line with its own line ending: the file is written back as it is.
	for (const line of text.split(/(?<=\n)/)) {
		if (piece.length + line.length > 8000) {
			pieces.push(piece);
			piece = '';
		}
		piece += line;
	}

	if (piece) pieces.push(piece);
	return pieces.map(escapeForC).map(p => `\t"${p}"`).join(',\n');
}

function escapeForC(text: string): string {
	return text
		.replace(/\\/g, '\\\\')
		.replace(/"/g, '\\"')
		.replace(/\r/g, '')
		.replace(/\n/g, '\\n"\n\t"')
		.replace(/\?\?/g, '?\\?'); // ??= and friends are trigraphs to an old compiler
}

const files = [pluginList()].map((file, index) => ({ ...file, name: `embedded_${index}` }));

writeFileSync(
	'./runtime/src/embedded.h',
	`// GENERATED by scripts/generate-embedded.ts - do not edit
// Source: scripts/server-files.ts
//
// What the module writes into addons/amxts on startup, and the natives table
// a plugin's imports are checked against.

// The build this module is of.
#define AMXTS_BUILD "${buildIdentity()}"

// The ABI of the plugins it loads: a plugin carries the one it was compiled
// against with the imports it uses, and is loaded when it is of this line and
// ground and g_nativesTable below has each of its imports the same.
#define AMXTS_ABI "${abiIdentity()}"

// The module's imports, a line each with its shape (runtime/natives.txt):
// the module's thunks, a plugin's imports and wamrc's signatures are three
// faces of this one list.
static const char *const g_nativesTable[] = {
${chunks(readFileSync('./runtime/natives.txt', 'utf8'))}
};

${files.map(f => `static const char *const ${f.name}[] = {\n${chunks(f.text)}\n};`).join('\n\n')}

struct EmbeddedFile {
	// Under addons/amxts.
	const char *path;
	const char *const *chunks;
	int count;
	// Whether the author owns this one, and it is written only when missing.
	int keep;
};

static const EmbeddedFile g_embedded[] = {
${files.map(f => `\t{ "${f.path}", ${f.name}, (int)(sizeof(${f.name}) / sizeof(${f.name}[0])), ${f.keep ? 1 : 0} },`).join('\n')}
};
`,
);

console.log(`runtime/src/embedded.h: ${files.length} files`);
