// runtime/src/host.h: the compiled host plugin as a C array, which the module
// writes into AMX Mod X's plugins folder on every start (scripts/compile-host.ts).

/** The header for the host plugin's bytes, 24 to a line. */
export function hostHeader(bytes: Uint8Array): string {
	const lines: string[] = [];
	for (let at = 0; at < bytes.length; at += 24) {
		lines.push(`\t${[...bytes.subarray(at, at + 24)].map(byte => `0x${byte.toString(16).padStart(2, '0')},`).join('')}`);
	}
	return `// GENERATED by scripts/compile-host.ts - do not edit
// Source: runtime/host/amxts_host.amxx
//
// The host plugin, compiled. The module writes it into AMX Mod X's plugins
// folder on every start and lists it for AMX Mod X to load (InstallHost in
// module.cpp), so the plugin and the module are always of one build.

static const unsigned char g_hostPlugin[] = {
${lines.join('\n')}
};
`;
}
