// runtime/src/image.h: the compiled natives' image as a C array, which the
// module loads every map (scripts/compile-image.ts).

/** The header for the image's bytes, 24 to a line. */
export function imageHeader(bytes: Uint8Array): string {
	const lines: string[] = [];
	for (let at = 0; at < bytes.length; at += 24) {
		lines.push(`\t${[...bytes.subarray(at, at + 24)].map(byte => `0x${byte.toString(16).padStart(2, '0')},`).join('')}`);
	}
	return `// GENERATED by scripts/compile-image.ts - do not edit
// Source: runtime/host/amxts_natives.amxx
//
// The natives' image, compiled: the module loads it with AMX Mod X's
// LoadAmxScript every map (LoadImage in module.cpp), so the image and the
// module are always of one build.

static const unsigned char g_nativesImage[] = {
${lines.join('\n')}
};
`;
}
