// The names `amxts upgrade` brings up to date (scripts/upgrade.ts): the API's
// names that were the engine's words and are now the player's, and the ones
// left out of the API, which the natives still reach.

/** Game events by their old name; each event's class follows its name. */
export const EVENTS: Record<string, string> = {
	addAccount: 'addMoney',
	restartRound: 'newRound',
	onRoundFreezeEnd: 'roundStart',
	hasRestrictItem: 'itemRestricted',
	cleanUpMap: 'mapReset',
	flPlayerFallDamage: 'fallDamage',
	fPlayerCanTakeDamage: 'canTakeDamage',
	fPlayerCanRespawn: 'canRespawn',
	fShouldSwitchWeapon: 'shouldSwitchWeapon',
	buyWeaponByWeaponId: 'buyWeapon',
	buyGunAmmo: 'buyAmmo',
	giveNamedItem: 'giveItem',
	giveC4: 'giveBomb',
	makeBomber: 'becomeBomber',
	makeVip: 'becomeVip',
	goToIntermission: 'intermission',
	precacheGenericI: 'precacheFile',
	precacheModelI: 'precacheModel',
	precacheSoundI: 'precacheSound',
	entSelectSpawnPoint: 'selectSpawnPoint',
	getPlayerSpawnSpot: 'spawnSpot',
	executeServerStringCmd: 'serverCommand',
	clientPrintf: 'consoleMessage',
	sendSayMessage: 'chatMessage',
	hintMessageEx: 'hintMessage',
	dropClient: 'disconnectClient',
	setClientUserInfoName: 'changeName',
	setClientUserInfoModel: 'changeModel',
	clientUserInfoChanged: 'userInfoChange',
	addPoints: 'addFrags',
	addPointsToTeam: 'addTeamScore',
	takeHealth: 'heal',
	addPlayerItem: 'addItem',
	removePlayerItem: 'removeItem',
	canHavePlayerItem: 'canHaveItem',
	deadPlayerWeapons: 'dropWeaponsOnDeath',
	kickBack: 'recoil',
	isPenetrableEntity: 'canShootThrough',
	startObserver: 'startSpectating',
	observerFindNextPlayer: 'spectateNext',
	observerIsValidTarget: 'canSpectate',
	impulseCommands: 'impulse',
	onSpawnEquip: 'spawnEquip',
	onEvent: 'gameEvent',
	pmDuck: 'duckMovement',
	pmJump: 'jumpMovement',
};

/** Game events out of the API, by the native that hooks them. */
export const HIDDEN_EVENTS: Record<string, string> = {
	alloc: 'RegisterHookChain(RH_ED_Alloc, ...)',
	free: 'RegisterHookChain(RH_ED_Free, ...)',
	directSet: 'RegisterHookChain(RH_Cvar_DirectSet, ...)',
	emitPings: 'RegisterHookChain(RH_SV_EmitPings, ...)',
	objectCaps: 'RegisterHookChain(RG_CBasePlayer_ObjectCaps, ...) or RegisterHam(Ham_ObjectCaps, ...)',
	getEntityInit: 'RegisterHookChain(RH_GetEntityInit, ...)',
	allowPhysent: 'RegisterHookChain(RH_SV_AllowPhysent, ...)',
	writeFullClientUpdate: 'RegisterHookChain(RH_SV_WriteFullClientUpdate, ...)',
	sendResources: 'RegisterHookChain(RH_SV_SendResources, ...)',
	reportAiState: 'RegisterHam(Ham_ReportAIState, ...)',
	useDecrement: 'RegisterHam(Ham_Weapon_UseDecrement, ...)',
	addDuplicate: 'RegisterHam(Ham_Item_AddDuplicate, ...)',
	overrideReset: 'RegisterHam(Ham_OverrideReset, ...)',
	onControls: 'RegisterHam(Ham_OnControls, ...)',
	updateOwner: 'RegisterHam(Ham_UpdateOwner, ...)',
};

/** What a value is, as far as the code says: the class whose names apply to it. */
export type Kind = 'Player' | 'Weapon' | 'Entity' | 'Game';

/** Every entity's fields and methods, a player's and a weapon's too. */
const ENTITY: Record<string, string> = {
	armorValue: 'armor',
	takeHealth: 'heal',
};

/** Fields and methods by their old name, for each kind of value. */
export const RENAMED: Record<Kind, Record<string, string>> = {
	Entity: ENTITY,
	Player: {
		...ENTITY,
		account: 'money',
		lastAccount: 'lastSentMoney',
		nextAccountHealthUpdate: 'nextScoreboardUpdate',
		clientHealth: 'healthSent',
		clientFov: 'fovSent',
		clientBattery: 'batterySent',
		clientHideHud: 'hideHudSent',
		clientActiveItem: 'activeItemSent',
		flashBattery: 'flashlightBattery',
		flashLightTime: 'flashlightTime',
		flgeigerDelay: 'geigerDelay',
		flgeigerRange: 'geigerRange',
		igeigerRangePrev: 'geigerRangePrev',
		idrowndmg: 'drownDamage',
		idrownrestored: 'drownRestored',
		currentammo: 'currentAmmo',
		gaitframe: 'gaitFrame',
		gaitsequence: 'playerGaitSequence',
		gaityaw: 'gaitYaw',
		prevgaitorigin: 'prevGaitOrigin',
		lastx: 'lastX',
		lasty: 'lastY',
		maxammoBuckshot: 'maxAmmoBuckshot',
		maxammo9mm: 'maxAmmo9mm',
		maxammo556nato: 'maxAmmo556nato',
		maxammo556natobox: 'maxAmmo556natobox',
		maxammo762nato: 'maxAmmo762nato',
		maxammo45acp: 'maxAmmo45acp',
		maxammo50ae: 'maxAmmo50ae',
		maxammo338mag: 'maxAmmo338mag',
		maxammo57mm: 'maxAmmo57mm',
		maxammo357sig: 'maxAmmo357sig',
		sbarString0: 'statusBarText',
		nextSBarUpdateTime: 'nextStatusBarUpdate',
		sndLast: 'lastSoundEntity',
		sndRange: 'soundRange',
		sndRoomtype: 'roomType',
		tbdPrev: 'timeBasedDamagePrev',
		punishedForTk: 'punishedForTeamKill',
		longJump: 'hasLongJump',
		velocityModifier: 'slowdown',
		sneaking: 'sneakingUntil',
		tank: 'mountedGun',
		train: 'trainControls',
		weapon: 'weaponHudValid',
		menu: 'openMenu',
		numSpawns: 'spawnCount',
		autoWepSwitch: 'autoSwitchWeapon',
		progressStart: 'progressBarStart',
		progressEnd: 'progressBarEnd',
		onTarget: 'aimingAtTarget',
		addPoints: 'addFrags',
		addPointsToTeam: 'addTeamScore',
		addPlayerItem: 'addItem',
		removePlayerItem: 'removeItem',
	},
	Weapon: {
		...ENTITY,
		inReload: 'isReloading',
		inSpecialReload: 'shotgunReloadStage',
		clientClip: 'clipSent',
		glock18Shoot: 'glockNextBurstShot',
		glock18ShotsFired: 'glockBurstShots',
		famasShoot: 'famasNextBurstShot',
		famasShotsFired: 'famasBurstShots',
		decreaseShotsFired: 'recoilResetTime',
		timeWeaponIdle: 'nextIdle',
		primaryAmmoType: 'ammoType',
	},
	Game: {
		accountCt: 'ctRoundBonus',
		accountTerrorist: 'terroristRoundBonus',
		c4Guy: 'bomber',
		c4Timer: 'bombTimer',
		numCt: 'ctCount',
		numTerrorist: 'terroristCount',
		numCtWins: 'ctWins',
		numTerroristWins: 'terroristWins',
		numSpawnableCt: 'spawnableCts',
		numSpawnableTerrorist: 'spawnableTerrorists',
		numConsecutiveCtLoses: 'ctLossStreak',
		numConsecutiveTerroristLoses: 'terroristLossStreak',
		restartRoundTime: 'newRoundTime',
		roundStartTimeReal: 'freezeStartTime',
		introRoundTime: 'freezeTime',
		freezePeriod: 'isFreezeTime',
		roundTerminating: 'roundEnding',
		tCantBuy: 'terroristsCantBuy',
		ctCantBuy: 'ctsCantBuy',
		unBalancedRounds: 'unbalancedRounds',
		levelInitialized: 'mapInitialized',
		endIntermissionButtonHit: 'intermissionSkipped',
		forceCameraValue: 'forceCamera',
		forceChaseCamValue: 'forceChaseCam',
		fadeToBlackValue: 'fadeToBlack',
		gameDesc: 'gameName',
	},
};

/** Every entity's field out of the API, by its member. */
const ENTITY_HIDDEN: Record<string, string> = { armorType: 'var_armortype' };

/** Fields out of the API, by the member a native reads them with, for each kind of value. */
export const HIDDEN: Record<Kind, Record<string, string>> = {
	Entity: ENTITY_HIDDEN,
	Player: {
		...ENTITY_HIDDEN,
		activity: 'm_Activity',
		idealActivity: 'm_IdealActivity',
		monsterState: 'm_MonsterState',
		idealMonsterState: 'm_IdealMonsterState',
		conditions: 'm_afConditions',
		memory: 'm_afMemory',
		enemyLkp: 'm_vecEnemyLKP',
		hackedGunPos: 'm_HackedGunPos',
		targetEnt: 'm_hTargetEnt',
		teamName: 'm_szTeamName',
	},
	Weapon: {
		...ENTITY_HIDDEN,
		fireFamas: 'm_Weapon_usFireFamas',
		fireGlock18: 'm_Weapon_usFireGlock18',
		lastFire: 'm_Weapon_flLastFire',
	},
	Game: {
		careerMatchMenuTime: 'm_fCareerMatchMenuTime',
		careerMatchWins: 'm_iCareerMatchWins',
		careerRoundMenuTime: 'm_fCareerRoundMenuTime',
		inCareerGame: 'm_bInCareerGame',
		roundWinDifference: 'm_iRoundWinDifference',
		msgPlayerVoiceMask: 'm_msgPlayerVoiceMask',
		msgRequestState: 'm_msgRequestState',
	},
};

/**
 * Old names common enough elsewhere - a menu's `menu`, a message's `weapon`,
 * a memory's `memory` - that a use on a value the code does not say is one of
 * ours is not listed.
 */
export const COMMON = new Set(['menu', 'weapon', 'memory', 'conditions', 'activity', 'train', 'tank', 'sneaking', 'onTarget', 'lastFire', 'teamName']);
